version: '3'

services:
  db:
    image: mikkezavala:db
    build:
      context: ./scripts/logbacksql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokemon_logs
      - MYSQL_USER=pokemon_user
      - MYSQL_PASSWORD=some_pass
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} -e \"SHOW DATABASES;\""]
      interval: 2s
      timeout: 15s
      retries: 20
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
      - ./scripts/logbacksql/init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - backend

  app:
    image: mikkezavala:app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

volumes:
  logger-data:

networks:
  backend:
